### ISSUE TITLE
Refactor configuration with SPI

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#21]
Now that YAML and TOML are available as config formats, it may be a good idea to split config model & parsing, by providing a config SPI.

Proposal:
- move package `org.moditect.layrry.internal.descriptor` from `layrry-launcher` into a new module named `layrry-config`.
- rename existing `LayersConfigParser` to `LayersConfigLoader` and use `ServiceLoader` to load instances of `LayersConfigParser` (new interface defined in following item) and consume them.
- add an interface `LayersConfigParser` with two methods:
  - boolean supports(Path configFile)
  - `LayersConfig parse(InputStream in)`
- move YAML support to a new module `layrry-config-yaml` and implement the new interface.
- move TOML support to a new module `layrry-config-toml` and implement the new interface.
- add these two new modules as dependencies on `layrry-launcher` and have the launcher invoke `LayersConfigLoader`.

**Comment by gunnarmorling** [comment]
Yes, that sounds great! Would you like to go for it?

**Comment by gunnarmorling** [comment]
We can close that one I think, right?
