### ISSUE TITLE
LarryLinkTest is a probable flaky test

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#24]
I've seen the following error when running on CI appearing a couple of times however it does not reproduce on a local build

    [INFO] Running com.example.layrry.links.integrationtest.LayrryLinksTest
    16:50:52.913 [main] INFO  c.e.l.l.c.i.LayrryLinksVerticle - Adding plug-in: PluginDescriptor [name=plugins-layrry-links-membership-1.0.0, moduleLayer=com.example.layrry.links.membership]
    16:50:53.151 [vert.x-eventloop-thread-0] INFO  c.e.l.l.c.i.LayrryLinksVerticle - Adding router for path: /routes
    16:50:53.179 [vert.x-eventloop-thread-0] INFO  c.e.l.l.c.i.LayrryLinksVerticle - Adding router for path: /members
    16:50:53.399 [vert.x-eventloop-thread-0] INFO  c.e.l.l.c.i.LayrryLinksVerticle - Server ready! Browse to http://localhost:8080/routes
    16:50:55.447 [pool-1-thread-1] INFO  c.e.l.l.c.i.LayrryLinksVerticle - Adding plug-in: PluginDescriptor [name=plugins-layrry-links-tournament-1.0.0, moduleLayer=]
    [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.462 s <<< FAILURE! - in com.example.layrry.links.integrationtest.LayrryLinksTest
    [ERROR] com.example.layrry.links.integrationtest.LayrryLinksTest.runLayers  Time elapsed: 9.397 s  <<< ERROR!
    org.awaitility.core.ConditionTimeoutException: Condition with com.example.layrry.links.integrationtest.LayrryLinksTest was not fulfilled within 5 seconds.
    	at com.example.layrry.links.integrationtest.LayrryLinksTest.runLayers(LayrryLinksTest.java:71)

**Comment by gunnarmorling** [comment]
Interesting, noticed that one, too. Not quite sure why, perhaps the env is just slow and a larger timeout will help?

**Comment by gunnarmorling** [comment]
> Adding plug-in: PluginDescriptor [name=plugins-layrry-links-tournament-1.0.0, moduleLayer=]

So it's not related to a timeout, rather there's no module layer present. Perhaps the filesystem event is processed before the copying of the actual plug-in jar is finished?

**Comment by gunnarmorling** [comment]
If it's that, it's a general problem, not limited to CI. Not sure how to handle it: when receiving the CREATE notification for the new plug-in directory, one would somehow have to wait until the contents of that directory has stabilized.

**Comment by aalmiray** [comment]
The vert.x projects were moved to `layrry-examples`, and the test was removed. However the underlying problem for test breakage in CI persists and it's captured in #39.
