### ISSUE TITLE
Rename layrry-launcher FAT JAR

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#25]
The current name is set to `${project.artifactId}-${project.version}-jar-with-dependencies.jar`.
It could be instead something like `layrry-cli-${project.version}.jar` or `layrry-runner-${project.version}.jar`.

**Comment by gunnarmorling** [comment]
Yes, good idea! While at that, mention in the README of running the non-fat JAR with custom config impls would be nice.
