### ISSUE TITLE
Split layrry-launcher module into embedded and cli

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#29]
The current `layrry-launcher` module allows 2 modes of operation:
- direct API usage for creating layers, suitable for embedding in a custom app launcher.
- configuration based (yaml, toml) launch with CLI options.

**Comment by aalmiray** [comment]
Hmm I guess it doesn't make much sense to have embeddable mode anyway.

**Comment by gunnarmorling** [comment]
You mean there's no point in having a public Layrry API, as it's going to be used most of the time configuration-based anyways? If so, I'm not sure I'd agree, I definitely see cases where you'd want to use the API. In any case not worth splitting into two modules IMO.

**Comment by aalmiray** [comment]
Well if API and CLI can be used separately then I'd still argue in favor of a module split because of publishing constraints. It makes sense for API to be a normal JAR while CLI is a shaded JAR. 

It's true that a single POM can produce more than 1 binary but I rather keep the 1-to-1 mapping. Also, this way API takes no favorites on config impl (YAML, TOML, etc) while CLI does.

**Comment by gunnarmorling** [comment]
Ah, yes, fair point about the config dependencies.

**Comment by gunnarmorling** [comment]
Done.
