### ISSUE TITLE
Are artifact classifiers supported?

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#30]
Launching a JavaFX application may require platform specific artifacts. OpenJFX ships artifacts with a classifier, whose short notation would be in the form `g:a:v:c`, such as `org.openjfx:javafx-base:11:mac`.

Currently configuring a module like that results in

    WARNING: Failed downloading org/openjfx/javafx-base/mac/javafx-base-mac.11 from https://repo1.maven.org/maven2/

**Comment by gunnarmorling** [comment]
Have you tried "org.openjfx:javafx-base:jar:mac:14.0.1"? This worked when I played around with JavaFx some time ago.

**Comment by aalmiray** [comment]
Ah, so `groupId:artifactId:type:classifier:version` instead? Yeah, that works.

I wish `type` could be omitted however given that classifiers are **not** supposed to be that common then I guess we'll have to keep it as is.

This format should be in the documentation just in case, wouldn't you agree?

**Comment by gunnarmorling** [comment]
> This format should be in the documentation just in case, wouldn't you
agree?

Yes, definitely. To give some background, Layrry is the result of a few
weekends/evenings work so far, hence there's many less-than-ideal issues
like that :)

>

**Comment by aalmiray** [comment]
Oh yeah, totally understand, Layrry is growing organically 😄

**Comment by aalmiray** [comment]
We may need to add limited expression evaluation capabilities as in the case for JavaFx you need to define a `classifier` but you would not want to fix the value in the file to keep it portable, that is,

    org.openjfx:javafx-base:jar:${detected.os}:11

The alternative is to write a config file for each target platform.

**Comment by aalmiray** [comment]
Closing in favor of #38
