### ISSUE TITLE
Add example using JavaFx

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/layrry#31]
I was thinking of something around plug-ins, which dynamically contribute/remove [tilesfx](https://github.com/HanSolo/tilesfx) widgets to some pane managed by a "core" module/layer. // @aalmiray WDYT?

**Comment by aalmiray** [comment]
I love the idea!

**Comment by brunoborges** [comment]
@hansolo will like this :)

**Comment by gunnarmorling** [comment]
I'm sure he will. If there's any taker, that'd be awesome, given my JavaFx knowledge is next to 0. I think in general, it could be rather similar to the existing Vert.x-based example, with an extension/service interface which here would add a tile and which would be used by some platform module + layer to update a shared panel or something.

**Comment by aalmiray** [comment]
If the Vert.x example already shows updating layers at runtime then certainly it can be used as starting point for JavaFX.

**Comment by aalmiray** [comment]
Setup a repository with a modular JavaFX app at https://github.com/aalmiray/modular-tiles
However Layrry complains that the `plugins` layer is not configured.

When testing I'd recommend launching Larry without jbang at the moment, as you can make adjustments locally and see what happens whereas `jbang layrry@moditect` will consume the layrry artifacts from the jitpack repo.

**Comment by gunnarmorling** [comment]
@aalmiray are you interested in picking this up? I was thinking about
asking around on Twitter whether there'd be any taker (JPMS + JavaFx +
layers might be interesting for some), but if you're on it already, I
probably shouldn't do that :)

>

**Comment by aalmiray** [comment]
Sure. The linked app works with JPMS but I can't make it work with dynamically loaded plugins like the Vert.x example does.

**Comment by aalmiray** [comment]
OK, so I figured out that I had the wrong expectation with dynamic plugins. The current setup has no content in the `plugins` directory. Because of this Layrry flags the layer as invalid and skips it, breaking the booting process.

Conclusion: a layer with `directory` cannot be empty at the moment.

Next I inspected the Vert.x plugin and found out the convention is to have `${artifactId}-${version}/${artifactId}-${version}.jar` thus I added `tile-clock-0.0.0/tile-clock-0.0.0.jar` to the `plugins` directory, but still got an error such as 

    Exception in thread "main" java.lang.IllegalArgumentException: Layer 'app': parent layer 'tile-clock-0.0.0' not configured yet
        at org.moditect.layrry.internal.LayersImpl.getParentLayers(LayersImpl.java:195)
        at org.moditect.layrry.internal.LayersImpl.run(LayersImpl.java:101)
        at org.moditect.layrry.Layrry.main(Layrry.java:53)

**Comment by aalmiray** [comment]
@gunnarmorling am I reading this right? the `layerBuilder` variable is ignored https://github.com/moditect/layrry/blob/master/layrry-launcher/src/main/java/org/moditect/layrry/internal/LayersFactory.java#L89

**Comment by aalmiray** [comment]
OK, OK, I think I've got it. 

1. Must follow naming convention for dynamic plugins, `${artifactId}-${version}/${artifactId}-${version}.jar`
2. empty directories are allowed.
3. my `layers.yaml` had layer `app` depend on `plugins` which caused the whole problem.

**Comment by aalmiray** [comment]
Alright, got https://github.com/aalmiray/modular-tiles as far as I can today. Both Maven and Gradle builds can prepackage plugins like the Vert.x example does. The `layers.yml` file looks quite close to the Vert.x example.

Observed behavior when `plugins` directory is empty and the application is launched:
- main window appears. Good.
- copy plugins from `app/modular-tile-app/target/plugins-prepared` into `plugins`. Nothing happens.

Observed behavior when `plugins` directory is **not** empty and the application is launched:

    Exception in thread "main" java.lang.IllegalArgumentException: java.lang.reflect.InvocationTargetException
        at org.moditect.layrry.internal.LayersImpl$Deployer.deploy(LayersImpl.java:307)
        at org.moditect.layrry.internal.LayersImpl.run(LayersImpl.java:122)
        at org.moditect.layrry.Layrry.main(Layrry.java:53)
    Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.moditect.layrry.internal.LayersImpl$Deployer.deploy(LayersImpl.java:304)
        ... 2 more
    Caused by: java.lang.IllegalStateException: Toolkit not initialized
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:410)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:405)
        at javafx.graphics/javafx.application.Platform.runLater(Platform.java:150)
        at org.kordamp.tiles.core@0.0.0/org.kordamp.tiles.core.TilePluginLifecycleListener.lambda$pluginAdded$1(TilePluginLifecycleListener.java:45)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.kordamp.tiles.core@0.0.0/org.kordamp.tiles.core.TilePluginLifecycleListener.pluginAdded(TilePluginLifecycleListener.java:43)
        at org.moditect.layrry.platform@1.0-SNAPSHOT/org.moditect.layrry.platform.internal.PluginLifecycleSupport.notifyPluginListenersOnAddition(PluginLifecycleSupport.java:42)
        ... 7 more

The exception occurs because there are UI elements being initialized before the JavaFX toolkit is initialized. Probably because plugins are being initialized eagerly before the main class is launched.

**Comment by aalmiray** [comment]
Alright, finally got it working up to a point. The exception shown above is skipped as the application detects if the toolkit has been initialized or not.

However I've found that Layrry will not initialize `PluginLifecycleListener`s if the directory is empty. Thus as I suspected the plugin directory must contain at least 1 module to begin with. This is consistent with the Vert.x example where the `memberships` plugin is available by default.

Another issue I faced is attempting to load tiles from the "plugins" layer which is of course not in the direct hierarchy of the layer that loads the Main class. Looking for an alternative.

**Comment by gunnarmorling** [comment]
Ok, nice that you seem to make progress!

> The exception shown above is skipped as the application detects if the toolkit has been initialized or not.

Right, I was about to suggest that, too. The lifecycle listener will be notified about all existing plug-ins at start-up, so in this case you'd have to delay the processing/registration of these until JavaFx is ready for it.

> However I've found that Layrry will not initialize PluginLifecycleListeners if the directory is empty.

Ah, that's interesting. Definitely something that needs fixing, ideally in a separate PR even.

> Another issue I faced is attempting to load tiles from the "plugins" layer which is of course not in the direct hierarchy of the layer that loads the Main class. Looking for an alternative

That one I don't understand yet. I'd expect a layer hierarchy (from top to bottom) like this: javafx/tilesfx -> core (with the tile contributor service interface) -> plugins (with contributor implementations) -> runner (with main class). Is this what you have? It should work, I think.

**Comment by aalmiray** [comment]
> Ah, that's interesting. Definitely something that needs fixing, ideally in a separate PR even.

Will open a ticket.

> That one I don't understand yet. I'd expect a layer hierarchy (from top to bottom) like this: javafx/tilesfx -> core (with the tile contributor service interface) -> plugins (with contributor implementations) -> runner (with main class). Is this what you have? It should work, I think.

That's what I thought as well but right now my `plugins` layer is not a parent of any other layer, ideally it should be a parent of the `app` layer. It does't work like that due to the empty directory issue.

**Comment by aalmiray** [comment]
Done.

https://github.com/moditect/layrry-examples/tree/master/modular-tiles
