### ISSUE TITLE
PluginLifecycleListeners will never be initialized if the starting directory is empty

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#33]
A layer defined for dynamically loaded plugins cannot be initially empty.

## Steps to Reproduce
1. build the project. Note that the vert.x plugin example runs correctly.
2. remove the membership directory from `vertx-example/layrry-links-runner/target/route-plugins/`
3. launch the vert.x example using `java -jar`.
4. copy the tournaments plugin to `vertx-example/layrry-links-runner/target/route-plugins/`
5. Note that not additional routes are loaded

**Comment by gunnarmorling** [comment]
So, seems the code in `LayersImpl` is a bit borked; there'll be only a `Deployer` instance if there's at least one plug-in already existing in the plug-in directory. And without that, the file system watcher won't be set-up for the plug-in dir.

**Comment by gunnarmorling** [comment]
Grabbing this one. I've figured where the issue is and will send a PR for fixing it shortly.

**Comment by gunnarmorling** [comment]
Done via #35.
