### ISSUE TITLE
Allow for OS placeholder in layers config files

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/layrry#38]
The JavaFX artifacts have a platform-specific classifier in their artifact ids, making a layers-config file referencing them not portable across platforms. See the discussion at https://github.com/aalmiray/modular-tiles for an example. This could be mitigated by allowing for a placeholder such as ${os} which would be resolved by Layrry in order to fetch the artifacts matching the current platform.

@aalmiray, WDYT?

**Comment by gunnarmorling** [comment]
Ah, just seeing you had the same idea for your modular-tiles launcher 👍 . So I think this should definitely be supported in Layrry itself.

**Comment by aalmiray** [comment]
Proposal:
- Add a 2nd arg to `org.moditect.layrry.config.LayersConfigParser.parse(Inputstream)` of type `Map<String, String>`.
- This map will contain computed values such as
  - detected OS related properties (same values as https://github.com/trustin/os-maven-plugin/)
  - OS classifiers as required by JavaFX
- implementors of `LayersConfigParser` will have the choice to interpolate values using the args map and `System.getProperties()`.

**Comment by gunnarmorling** [comment]
What would be the motivation for pushing this behavior into `LayersConfigParser` implementations? Do you expect different behaviors between YAML, TOML, or other formats? How about centralizing placeholder resolution in `LayersImpl` instead, which is also where we deal with dependency resolution itself?

**Comment by aalmiray** [comment]
True, having implementors be responsible for evaluating expressions may lead into duplicate code.
OTOH Layrry would have to decide a standard expression format (say, ${prop}) that every parser must follow. What if that format is incompatible or has special meaning (i.e, ${prop} is  Groovy's expression format as well, one must write it as \${foo} to skip evaluation during read).

**Comment by gunnarmorling** [comment]
How about having parsers convert whatever custom placeholder syntax they prefer into a canonical one? I.e. the parsed config model would contain the placeholders in one uniform way, no matter what config file format was chosen, and `LayersImpl` would resolve this then?

**Comment by aalmiray** [comment]
Right. I was just wondering if Layrry states that the data found in `LayersConfig` as parsed from X implementor must always be `${pro}`. If that's the case then OK.

**Comment by gunnarmorling** [comment]
We make the rules :) I think it's a fair assumption provided its documented in the parser interface contract.

**Comment by aalmiray** [comment]
OK, what about this: let `LayersConfigLoader` perform placeholder substitution **before** letting `LayersConfigParser` implementation do their thing. This allows for substitutions to occur in one go, instead of traversing the `LayersConfig` object graph and making substitutions to each module definition independently.

I'd also suggest adding `static LayersConfig loadConfig(Inputstream inputStream)` to `LayersConfigLoader`.

**Comment by gunnarmorling** [comment]
Wouldn't this require `LayersConfigLoader` to know about the format-specific placeholder formats, though?

**Comment by aalmiray** [comment]
Not necessarily. Say the loader assumes the input is a Mustache template (like the one in the modular-tiles app). Applies value substitutions and then handles the replaced text (as inpustream) to the config parser. The problem here is invoking the correct parser without having the loader call one in particular in a direct fashion.

**Comment by gunnarmorling** [comment]
Ok, but then you have essentially defined one single placeholder format
(Mustache syntax), right? I thought you'd be concerned about this colliding
with specific config formats.

>

**Comment by aalmiray** [comment]
Exactly, yes, if the given input was still in the "native" format. But if a single template format is preferred (say Mustache (which is my current preference given: speed, size, no deps)) then it does not matter as replacements will be evaluated before the format itself is affected.

**Comment by gunnarmorling** [comment]
Ok, that makes sense. Seems like we got a plan then?

**Comment by aalmiray** [comment]
Alright, so we go with Mustache template, the Loader performs substitutions, then asks which Parser can handle the inputstream (using the input Path), finally passes the input stream to the selected parser.

**Comment by gunnarmorling** [comment]
Yep, sounds good to me1
