### ISSUE TITLE
Update javafx.os.classifier to os.detected.jfxname

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#51]
There's no convention for the JavaFX os classifier however Jbang chose the later. Should  we align?

**Comment by gunnarmorling** [comment]
To clarify you mean that JBang as a similar notion of a JavaFX classifier property already? If so yes, let's use the same one, that makes sense.

**Comment by aalmiray** [comment]
Yes, JBang supports running JavaFX apps https://github.com/jbangdev/jbang#system-properties-and-environment-variables

**Comment by aalmiray** [comment]
Fixed with https://github.com/moditect/layrry/commit/38dc0e476a140b00b062afe454d7a018900a630f
