### ISSUE TITLE
Support OS classifiers from LWJGL

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#55]
As seen at https://repo1.maven.org/maven2/org/lwjgl/lwjgl/3.2.3/ LWJGL requires the following classifiers

* linux-arm32
* linux-arm64
* linux
* macosx
* windows-x86
* windows

Similarly as it was done for JavaFX (#51) an extra classifier such as `os.detected.lwjglname` could be added.

Suggested by @sormuras.

**Comment by aalmiray** [comment]
The `os-maven-plugin` does not yet detect `arm64`. This value may be a bit difficult to determine based on the host platform -> https://stackoverflow.com/questions/10846105/all-possible-values-os-arch-in-32bit-jre-and-in-64bit-jre

**Comment by gunnarmorling** [comment]
Done.
