### ISSUE TITLE
Add to the Readme that only Hotspot is supported

### ISSUE THREAD

**Issue by Thihup** [moditect/layrry#63]
As the project uses the JFR events, only Hotspot implementation supports it. The OpenJ9 doesn't have those classes so the build fails with NoClassDefFoundError

**Comment by gunnarmorling** [comment]
Thanks, that's interesting. Which version of OpenJ9 is this? I was under the impression that any Java implementation >= 11 comes with JFR.

**Comment by Thihup** [comment]
Unfortunately, JFR is specific to the Hotspot. I tried using OpenJ9 15.
You can give it a try using it from here: https://adoptopenjdk.net/?variant=openjdk15&jvmVariant=openj9

**Comment by aalmiray** [comment]
It may be the case that *every* JDK implementation based on OpenJDK is capable of triggering JFR events https://en.wikipedia.org/wiki/JDK_Flight_Recorder

It's my understanding that OpenJ9 is a clean room implementation of the JDK spec and does not inherit from OpenJDK, isn't it? 

However JFR was delivered to OpenJDK via JEP 328 (https://openjdk.java.net/jeps/328). JEPs are used to design and deliver features to Java SE. If so, JEP 328 makes JFR part of the Java SE Spec governing Java 11, which means JFR must be implemented by vendors that claim compatibility with Java11 as part of JTCK compliance, isn't that the case? If this is true, _and_ JFR is indeed a part of the Java SE spec then the implicit assumption in Layrry is that it can be used with any JTCK compliant implementation.

**Comment by Thihup** [comment]
As far as I can tell, OpenJ9 uses the same class library from OpenJDK, however, the JVM itself is a clean room implementation of JVM spec.
If I recall correctly, only the "java.*" modules are supported indeed the public API. The "jdk." modules are an implementation detail (for instance, the jdk.httpserver module). 
I don't know exactly, but I think the JEPs can deliver both implementation-specific features and public features. For instance, the JEP 373 (http://openjdk.java.net/jeps/373) is mainly focused on implementation detail, and I guess another compliant JDK implementation may not need to rework its functionality.
