### ISSUE TITLE
Configure publication to Maven Central using Github actions

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#86]
Bintray is sunseting on May 1st 2021. We need an alternative

https://github.com/adobe/S3Mock/blob/main/.github/workflows/maven-release.yml

https://github.com/raphw/byte-buddy/blob/master/.github/workflows/main.yml#L93

https://bjansen.github.io/java/2021/02/03/deploying-to-maven-central-using-github-actions.html

**Comment by gunnarmorling** [comment]
Yes, would love to do this via GH Actions. But let's make sure to use a dedicated user account for that. If needed, I can request a new Sonatype user id and have it assigned.

**Comment by aalmiray** [comment]
We will need github tokens and other secrets as well. We can have them for this repository alone or setup at the moditect org to be reused by other projects that may need publication to MC.

**Comment by gunnarmorling** [comment]
Yes, if we can do this once for the entire ModiTect org, that would be
great. One of the reasons that ModiTect itself isn't evolving a lot is
that releases were such a hassle.

>

**Comment by aalmiray** [comment]
It's overhaulin' time! Vroom vroom!
