### ISSUE TITLE
Do not apply proxy settings automatically

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#88]
Proxy settings should be applied **if an only if** a proxy is needed. Current code (`1.0.0.Alpha1`) fails when no proxy is required yet one is applied to the HttpClient.

**Comment by gunnarmorling** [comment]
@aalmiray, added this and #87 to a new milestone, 1.0.0.Beta1. I think it makes sense to start tracking items like that now that the first release went out.

**Comment by gunnarmorling** [comment]
Also, as a good measure, let's try and have an issue that can be referenced for each (substantial) commit. No need for that for typo fixes etc. I put the PR from @joschi into that milestone too, as there was no issue for it. Let's usually avoid that though and only track issues in milestones.
